/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { BackupRequestBuilderRequestsMetadata, type BackupRequestBuilder } from './backup/index';
// @ts-ignore
import {
  DisasterRecoveryRequestBuilderRequestsMetadata,
  type DisasterRecoveryRequestBuilder,
} from './disasterRecovery/index';
// @ts-ignore
import { SeedRequestBuilderRequestsMetadata, type SeedRequestBuilder } from './seed/index';
// @ts-ignore
import { StatusRequestBuilderRequestsMetadata, type StatusRequestBuilder } from './status/index';
// @ts-ignore
import {
  type BaseRequestBuilder,
  type KeysToExcludeForNavigationMetadata,
  type NavigationMetadata,
} from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/management
 */
export interface ManagementRequestBuilder extends BaseRequestBuilder<ManagementRequestBuilder> {
  /**
   * The backup property
   */
  get backup(): BackupRequestBuilder;
  /**
   * The disasterRecovery property
   */
  get disasterRecovery(): DisasterRecoveryRequestBuilder;
  /**
   * The seed property
   */
  get seed(): SeedRequestBuilder;
  /**
   * The status property
   */
  get status(): StatusRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ManagementRequestBuilderUriTemplate = '{+baseurl}/api/management';
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ManagementRequestBuilderNavigationMetadata: Record<
  Exclude<keyof ManagementRequestBuilder, KeysToExcludeForNavigationMetadata>,
  NavigationMetadata
> = {
  backup: {
    requestsMetadata: BackupRequestBuilderRequestsMetadata,
  },
  disasterRecovery: {
    requestsMetadata: DisasterRecoveryRequestBuilderRequestsMetadata,
  },
  seed: {
    requestsMetadata: SeedRequestBuilderRequestsMetadata,
  },
  status: {
    requestsMetadata: StatusRequestBuilderRequestsMetadata,
  },
};
/* tslint:enable */
/* eslint-enable */
