/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createScheduleRecipeDtoFromDiscriminatorValue, serializeScheduleRecipeDto, type ScheduleRecipeDto } from '../../../models/index';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FillTheGapGetResponse}
 */
// @ts-ignore
export function createFillTheGapGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFillTheGapGetResponse;
}
/**
 * The deserialization information for the current model
 * @param FillTheGapGetResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFillTheGapGetResponse(fillTheGapGetResponse: Partial<FillTheGapGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { fillTheGapGetResponse.data = n.getCollectionOfObjectValues<ScheduleRecipeDto>(createScheduleRecipeDtoFromDiscriminatorValue); },
    }
}
export interface FillTheGapGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * The data property
     */
    data?: ScheduleRecipeDto[] | null;
}
/**
 * Builds and executes requests for operations under /api/schedule/fill-the-gap
 */
export interface FillTheGapRequestBuilder extends BaseRequestBuilder<FillTheGapRequestBuilder> {
    /**
     * Returns up to 5 recipe suggestions for an empty planner slot. Recipes already assigned to CalendarEvents in the target week (identified by weekOffset) are excluded. Results are sorted by rotation sort: LastCookedDate ASC NULLS FIRST (never-cooked recipes first), then VoteCount DESC as a tiebreaker. RecipeMatches (family favourites) are returned before DiscoveryRecipes fallback results.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FillTheGapGetResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<FillTheGapRequestBuilderGetQueryParameters> | undefined) : Promise<FillTheGapGetResponse | undefined>;
    /**
     * Returns up to 5 recipe suggestions for an empty planner slot. Recipes already assigned to CalendarEvents in the target week (identified by weekOffset) are excluded. Results are sorted by rotation sort: LastCookedDate ASC NULLS FIRST (never-cooked recipes first), then VoteCount DESC as a tiebreaker. RecipeMatches (family favourites) are returned before DiscoveryRecipes fallback results.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<FillTheGapRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Returns up to 5 recipe suggestions for an empty planner slot. Recipes already assigned to CalendarEvents in the target week (identified by weekOffset) are excluded. Results are sorted by rotation sort: LastCookedDate ASC NULLS FIRST (never-cooked recipes first), then VoteCount DESC as a tiebreaker. RecipeMatches (family favourites) are returned before DiscoveryRecipes fallback results.
 */
export interface FillTheGapRequestBuilderGetQueryParameters {
    /**
     * Week offset from the current week (0 = this week, 1 = next week, -1 = last week). Recipes already assigned to any day in the target week are excluded from results.
     */
    weekOffset?: number;
}
/**
 * Serializes information the current object
 * @param FillTheGapGetResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFillTheGapGetResponse(writer: SerializationWriter, fillTheGapGetResponse: Partial<FillTheGapGetResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!fillTheGapGetResponse || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<ScheduleRecipeDto>("data", fillTheGapGetResponse.data, serializeScheduleRecipeDto);
    writer.writeAdditionalData(fillTheGapGetResponse.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const FillTheGapRequestBuilderUriTemplate = "{+baseurl}/api/schedule/fill-the-gap{?weekOffset*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const FillTheGapRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: FillTheGapRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createFillTheGapGetResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
