/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createManagementTaskAcceptedResponseFromDiscriminatorValue, type ManagementTaskAcceptedResponse } from '../../../models/index';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/management/disaster-recovery
 */
export interface DisasterRecoveryRequestBuilder extends BaseRequestBuilder<DisasterRecoveryRequestBuilder> {
    /**
     * Trigger an asynchronous disaster recovery
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ManagementTaskAcceptedResponse>}
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ManagementTaskAcceptedResponse | undefined>;
    /**
     * Trigger an asynchronous disaster recovery
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const DisasterRecoveryRequestBuilderUriTemplate = "{+baseurl}/api/management/disaster-recovery";
/**
 * Metadata for all the requests in the request builder.
 */
export const DisasterRecoveryRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: DisasterRecoveryRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createManagementTaskAcceptedResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
