/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { GroceryRequestBuilderRequestsMetadata, type GroceryRequestBuilder } from './grocery/index';
// @ts-ignore
import {
  SmartDefaultsRequestBuilderRequestsMetadata,
  type SmartDefaultsRequestBuilder,
} from './smartDefaults/index';
// @ts-ignore
import {
  type BaseRequestBuilder,
  type KeysToExcludeForNavigationMetadata,
  type NavigationMetadata,
} from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/schedule/{weekOffset}
 */
export interface WithWeekOffsetItemRequestBuilder extends BaseRequestBuilder<WithWeekOffsetItemRequestBuilder> {
  /**
   * The grocery property
   */
  get grocery(): GroceryRequestBuilder;
  /**
   * The smartDefaults property
   */
  get smartDefaults(): SmartDefaultsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithWeekOffsetItemRequestBuilderUriTemplate = '{+baseurl}/api/schedule/{weekOffset}';
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithWeekOffsetItemRequestBuilderNavigationMetadata: Record<
  Exclude<keyof WithWeekOffsetItemRequestBuilder, KeysToExcludeForNavigationMetadata>,
  NavigationMetadata
> = {
  grocery: {
    requestsMetadata: GroceryRequestBuilderRequestsMetadata,
  },
  smartDefaults: {
    requestsMetadata: SmartDefaultsRequestBuilderRequestsMetadata,
  },
};
/* tslint:enable */
/* eslint-enable */
