/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import {
  createSettingsDtoFromDiscriminatorValue,
  serializeSettingsDto,
  type SettingsDto,
} from '../../../models/index';
// @ts-ignore
import {
  type AdditionalDataHolder,
  type BaseRequestBuilder,
  type Parsable,
  type ParsableFactory,
  type ParseNode,
  type RequestConfiguration,
  type RequestInformation,
  type RequestsMetadata,
  type SerializationWriter,
} from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WithKeyGetResponse}
 */
// @ts-ignore
export function createWithKeyGetResponseFromDiscriminatorValue(
  parseNode: ParseNode | undefined
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoWithKeyGetResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WithKeyPostResponse}
 */
// @ts-ignore
export function createWithKeyPostResponseFromDiscriminatorValue(
  parseNode: ParseNode | undefined
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoWithKeyPostResponse;
}
/**
 * The deserialization information for the current model
 * @param WithKeyGetResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWithKeyGetResponse(
  withKeyGetResponse: Partial<WithKeyGetResponse> | undefined = {}
): Record<string, (node: ParseNode) => void> {
  return {
    data: (n) => {
      withKeyGetResponse.data = n.getObjectValue<SettingsDto>(
        createSettingsDtoFromDiscriminatorValue
      );
    },
  };
}
/**
 * The deserialization information for the current model
 * @param WithKeyPostResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWithKeyPostResponse(
  withKeyPostResponse: Partial<WithKeyPostResponse> | undefined = {}
): Record<string, (node: ParseNode) => void> {
  return {
    data: (n) => {
      withKeyPostResponse.data = n.getObjectValue<SettingsDto>(
        createSettingsDtoFromDiscriminatorValue
      );
    },
  };
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WithKeyGetResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWithKeyGetResponse(
  writer: SerializationWriter,
  withKeyGetResponse: Partial<WithKeyGetResponse> | undefined | null = {},
  isSerializingDerivedType: boolean = false
): void {
  if (!withKeyGetResponse || isSerializingDerivedType) {
    return;
  }
  writer.writeObjectValue<SettingsDto>('data', withKeyGetResponse.data, serializeSettingsDto);
  writer.writeAdditionalData(withKeyGetResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WithKeyPostResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWithKeyPostResponse(
  writer: SerializationWriter,
  withKeyPostResponse: Partial<WithKeyPostResponse> | undefined | null = {},
  isSerializingDerivedType: boolean = false
): void {
  if (!withKeyPostResponse || isSerializingDerivedType) {
    return;
  }
  writer.writeObjectValue<SettingsDto>('data', withKeyPostResponse.data, serializeSettingsDto);
  writer.writeAdditionalData(withKeyPostResponse.additionalData);
}
export interface WithKeyGetResponse extends AdditionalDataHolder, Parsable {
  /**
   * The data property
   */
  data?: SettingsDto | null;
}
/**
 * Builds and executes requests for operations under /api/settings/{key}
 */
export interface WithKeyItemRequestBuilder extends BaseRequestBuilder<WithKeyItemRequestBuilder> {
  /**
   * Get a setting by key
   * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
   * @returns {Promise<WithKeyGetResponse>}
   */
  get(
    requestConfiguration?: RequestConfiguration<object> | undefined
  ): Promise<WithKeyGetResponse | undefined>;
  /**
   * Upsert a setting by key
   * @param body The request body
   * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
   * @returns {Promise<WithKeyPostResponse>}
   */
  post(
    body: SettingsDto,
    requestConfiguration?: RequestConfiguration<object> | undefined
  ): Promise<WithKeyPostResponse | undefined>;
  /**
   * Get a setting by key
   * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
   * @returns {RequestInformation}
   */
  toGetRequestInformation(
    requestConfiguration?: RequestConfiguration<object> | undefined
  ): RequestInformation;
  /**
   * Upsert a setting by key
   * @param body The request body
   * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
   * @returns {RequestInformation}
   */
  toPostRequestInformation(
    body: SettingsDto,
    requestConfiguration?: RequestConfiguration<object> | undefined
  ): RequestInformation;
}
export interface WithKeyPostResponse extends AdditionalDataHolder, Parsable {
  /**
   * The data property
   */
  data?: SettingsDto | null;
}
/**
 * Uri template for the request builder.
 */
export const WithKeyItemRequestBuilderUriTemplate = '{+baseurl}/api/settings/{key}';
/**
 * Metadata for all the requests in the request builder.
 */
export const WithKeyItemRequestBuilderRequestsMetadata: RequestsMetadata = {
  get: {
    uriTemplate: WithKeyItemRequestBuilderUriTemplate,
    responseBodyContentType: 'application/json',
    adapterMethodName: 'send',
    responseBodyFactory: createWithKeyGetResponseFromDiscriminatorValue,
  },
  post: {
    uriTemplate: WithKeyItemRequestBuilderUriTemplate,
    responseBodyContentType: 'application/json',
    adapterMethodName: 'send',
    responseBodyFactory: createWithKeyPostResponseFromDiscriminatorValue,
    requestBodyContentType: 'application/json',
    requestBodySerializer: serializeSettingsDto,
    requestInformationContentSetMethod: 'setContentFromParsable',
  },
};
/* tslint:enable */
/* eslint-enable */
