@recipeId = 5df6b7da-4537-4b06-bae6-e8278ce2d1a9

### Get discovery categories
# Returns categories that have recipes available for discovery for this member.
GET {{baseUrl}}/api/discovery/categories
X-Family-Member-Id: {{familyMemberId}}
Accept: application/json
X-Hearth-Secret: {{hearthSecret}}

### Get discovery stack
# Returns the list of discoverable recipes the member hasn't voted on yet.
GET {{baseUrl}}/api/discovery
X-Family-Member-Id: {{familyMemberId}}
Accept: application/json
X-Hearth-Secret: {{hearthSecret}}

### Get discovery stack by category
GET {{baseUrl}}/api/discovery?category=Chicken
X-Family-Member-Id: {{familyMemberId}}
Accept: application/json
X-Hearth-Secret: {{hearthSecret}}

### Vote on a recipe (Like - Value 1)
POST {{baseUrl}}/api/discovery/{{recipeId}}/vote
X-Family-Member-Id: {{familyMemberId}}
Content-Type: application/json
X-Hearth-Secret: {{hearthSecret}}

{
    "vote": 1
}

### Vote on a recipe (Skip - Value 2)
POST {{baseUrl}}/api/discovery/{{recipeId}}/vote
X-Family-Member-Id: {{familyMemberId}}
Content-Type: application/json
X-Hearth-Secret: {{hearthSecret}}

{
    "vote": 2
}
