/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { BulkRequestBuilderRequestsMetadata, type BulkRequestBuilder } from './bulk/index';
// @ts-ignore
import {
  type BaseRequestBuilder,
  type KeysToExcludeForNavigationMetadata,
  type NavigationMetadata,
} from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/recipes/imports
 */
export interface ImportsRequestBuilder extends BaseRequestBuilder<ImportsRequestBuilder> {
  /**
   * The bulk property
   */
  get bulk(): BulkRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ImportsRequestBuilderUriTemplate = '{+baseurl}/api/recipes/imports';
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ImportsRequestBuilderNavigationMetadata: Record<
  Exclude<keyof ImportsRequestBuilder, KeysToExcludeForNavigationMetadata>,
  NavigationMetadata
> = {
  bulk: {
    requestsMetadata: BulkRequestBuilderRequestsMetadata,
  },
};
/* tslint:enable */
/* eslint-enable */
